In [ ]:
arr = list(input().split())
mid = int(len(arr) / 2)
first_half = arr[: mid: ].copy()
second_half = arr[mid: : ].copy()

if mid % 2 == 0:
  start = 0
else:
  start = 1

temp = 0

for i in range(start, int(len(second_half) / 2), 2):
    temp = second_half[i]
    second_half[i] = second_half[-i - 1]
    second_half[-i - 1] = temp

print(first_half + second_half)


0 1 2 3 4 5 6 7 8 9 
['0', '1', '2', '3', '4', '5', '8', '7', '6', '9']


In [ ]:
arr = ['0', '1', '2', '3', '4', '5', '8', '7', '6', '9']
res = list(map(int, arr))
res2 = [int(x) for x in arr]
print(arr)
print(res)
print(res2)

['0', '1', '2', '3', '4', '5', '8', '7', '6', '9']
[0, 1, 2, 3, 4, 5, 8, 7, 6, 9]
[0, 1, 2, 3, 4, 5, 8, 7, 6, 9]


In [ ]:
arr = list(input().split())
forward = 0
back = 0

for i in range(1, 5):
  if i % 2 == 0:
    forward = arr[i]
    back = arr[-(i - 1)]
    arr[i] = back
    arr[-(i - 1)] = forward

print(arr)

0 1 2 3 4  5 6 7 8 9
['0', '1', '9', '3', '7', '5', '6', '4', '8', '2']


In [ ]:
l = [5,8,7,9,5,7,34,0,5,8,1]

l[4:-4:-3]

# 5

[]

In [ ]:
arr = list(map(int, input().split()))
new_arr = []

for i in range (len(arr)):
  new_arr.extend([arr[i] - 1])

print(new_arr)

1 2 3 4 5 6 7  9
[0, 1, 2, 3, 4, 5, 6, 8]


In [ ]:
arr = list(map(int, input().split()))
new_arr = []

for i in range (len(arr)):
  if i % 2 == 0:
    new_arr.extend([arr[i] ** 2])
  else:
    new_arr.extend([arr[i] ** 3])

print(new_arr)

1 2 3 4 5 6 7 8 9 
[1, 8, 9, 64, 25, 216, 49, 512, 81]


In [ ]:
word = str(input())
word_dict = dict()

for symbol in word:
  word_dict[symbol] = ord(symbol)

print(min(word_dict, key=word_dict.get))

agfhjsgfjs
a


In [ ]:
word = str(input())
new_word = ''

for ind, symbol in enumerate(word):
   new_word += chr(ord(symbol) + ind)

print(new_word)

abcdef
acegik


In [ ]:
import numpy as np

arr_16 = np.arange(256).reshape(16, 16)

arr_4 = np.zeros((4, 4), dtype=int)

for i in range(4):
    for j in range(4):
        submatrix = arr_16[i*4:(i+1)*4, j*4:(j+1)*4]
        arr_4[i, j] = np.sum(submatrix)

print(arr_4)


[[ 408  472  536  600]
 [1432 1496 1560 1624]
 [2456 2520 2584 2648]
 [3480 3544 3608 3672]]


In [ ]:
import numpy as np

lines = np.array([[2, -1, 3],
                  [1, 1, -5],
                  [-3, 4, 2],
                  [0, 1, -2]])

point = np.array([6, 7])

dist = []

for i, line in enumerate(lines):
  first = np.abs(line[0] * point [0] + line[1] * point [1] + line[2])
  second = np.sqrt(line[0] ** 2 + line[1] ** 2)
  dist.insert(i, first / second)

dist = np.array(dist)

print(f"""минимальное расстояние {dist.min()}
прямая с минимальным расстоянием {lines[np.argmin(dist)]}""")

минимальное расстояние 2.4
прямая с минимальным расстоянием [-3  4  2]
